### ISSUE TITLE
Implementar select para representación Bonds (Lines)

### ISSUE THREAD

**Issue by tripplab** [tripplab/HTMoLv3.5#14]
Cuando la representación es Bonds, y se introdce en la consola el comando

> select 0:0:A

se genera el siguiente error en el navegador:
```
Uncaught TypeError: Cannot set property '-1156' of undefined
    at ProcesarSeleccion (ButtonsFunctions.js:341)
    at Main.Parse (Main.js:897)
    at Main.onTestChange (Main.js:972)
    at HTMLTextAreaElement.onkeypress (VM993 HTMoL.html:1478)
```

**Comment by tripplab** [comment]
Quizá esto no sea crítico si la selección de átomos en representación Bonds funciona programáticamente (desde el HTML) como se especifica en #3

**Comment by tripplab** [comment]
No fue así. Cuando `RepresentacionInicial='Bonds'`, sigue dando un error:
```
Uncaught TypeError: Cannot set property '-144' of undefined
    at ProcesarSeleccion (http://148.247.230.41/HTMoLv3.5/js/ButtonsFunctions.js:341:59)
    at Main.Parse (http://148.247.230.41/HTMoLv3.5/js/Main.js:898:17)
    at http://148.247.230.41/HTMoLv3.5/js/InicializarRepre.js:7:14
    at Array.forEach (native)
    at InitBufRepreDefault (http://148.247.230.41/HTMoLv3.5/js/InicializarRepre.js:6:10)
    at webGLStart (http://148.247.230.41/HTMoLv3.5/js/MainHTMoL.js:1236:9)
    at onload (http://148.247.230.41/HTMoLv3.5/HTMoL.html#:166:32)
```
Para que funcione, se debe implementar "select" para la representación "Bonds". Código de `function ProcesarSeleccion()` en `ButtonsFunctions.js` (linea 324)
